const userTypes = {
    CHECK_USER_SESSION: 'CHECK_USER_SESSION',
    EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
    GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
    RESET_PASSWORD_START: 'RESET_PASSWORD_START',
    RESET_USER_STATE: 'RESET_USER_STATE',
    RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
    SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
    SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
    SIGN_UP_USER_START: 'SIGN_UP_USER_START',
    USER_ERROR: 'USER_ERROR'
};

export default userTypes